var speakers = [
    {id: 0, name: "Jeet Kumar", pic: "jeet.jpg", title: "CEO", bio: "With a degree in electronics and communication, years of experience, and a knack for developing strategic partnerships, Jeet bridges the gap between product vision and team execution. Before co-founding In Time Tec, Jeet was responsible for creating and managing next-generation print device architecture for Hewlett Packard’s printer firmware organization. He was awarded 10 U.S. patents for his work. Jeet has also co-authored five articles in Industry Leading Embedded System Publications. Jeet actively pursues continuing education in business, leadership, and current technology trends. In his free time, Jeet enjoys a competitive game of squash and spending time with his family."},
    {id: 1, name: "Rakesh Kumar Sawan", pic: "rksawan.jpg", title: "CTO", bio: "Rakesh´s main focus and primary strength is solving customer’s pain points. Before co-founding In Time Tec, Rakesh was a technical architect for Hewlett-Packard. He spent almost 10 years developing and designing software Rakesh started his career as a developer primarily working on C/C++ and Java. He then spent most of his time at HP designing and developing Enterprise class server applications primarily focused on extensibility, performance and scalability. Before leaving, he was the key member of the Architecture Group responsible for the HP ePrint Cloud offering. Rakesh went to college at Govt. Engineering College Ujjain and graduated in 1997. He then completed post graduation from Indian Institute of Technology, Kharagpur in 1999. He earned the title of software engineer immediately after graduation at Dharma Systems Ltd."},
    {id: 2, name: "Sandeep Jain", pic: "sandeep.jpg", title: "Managing Director", bio: "Sandeep has always been good with numbers, a fitting skill for managing In Time Tec’s finances, operations, and human resources. As an In Time Tec co-founder, Sandeep creatively removes obstacles and limitations that prevent business growth. He is equipped with a degree in engineering from University of Rajasthan, India (MNIT, Jaipur) and a MBA in Finance from Indira Gandhi National Open University, India. Sandeep’s entrepreneurial spirit has led to his involvement in the real estate market. He pursues real estate ventures to provide affordable housing for families in Rajasthan. When not in the office, he enjoys reading, writing, and being active in his community."},
    {id: 3, name: "Rob Tuft", pic: "rob.jpg", title: "VP of Engineering", bio: "As acting VP of Engineering, Rob applies the latest industry best practices and technologies into In Time Tec’s software development processes and quality initiatives. Rob works closely with clients, helping organizations extend development capacity by blending offshore capabilities and process innovation with local project management. By integrating Agile software development processes, Rob creates efficient workflows and manages ongoing engineering. Rob came to InTimeTec with a rich history in the engineering industry. Rob spent 12 years at Hewlett Packard as a Senior Software Engineer, working in a variety of development, test, and process improvement roles. Rob received his Bachelors of Science in Electrical and Computer Engineering at Brigham Young University. He received his MBA in Information Technology from Boise State University, and also holds his MS in Information Technology, System Design & Development from Capella University. Most recently Rob became certified as a Scrum Master. Rob´s dedication to his career transcends to other areas in his life as well. First and foremost, his family of 6 comes first. They love swimming and exploring the great outdoors together. Rob is also an adventurous outdoorsman, and an experienced climber. Rob´s bucket includes climbing every peak over 11,000 feet in Idaho! He´s at 75 and counting."},
];

exports.findAll = function (req, res, next) {
    res.send(speakers);
};

exports.findById = function (req, res, next) {
    var id = req.params.id;
    res.send(speakers[id]);
};